# Numpy es una biblioteca fundamental para la computacion cientifica


In [1]:
import numpy as np

In [4]:
lista_numeros = [1,3,5,6,7,9]

array_np = np.array(lista_numeros)

array_np

# Multidimensional
lista_md = [[1,2,3],[4,5,6]]
lista_md

[[1, 2, 3], [4, 5, 6]]

In [5]:
# np.zeros() Crea un array de ceros

array_zeros = np.zeros((3, 4))
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# np.ones() Crea un array de unos

array_ones = np.ones((3, 4))
array_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# np.arange() Crea un array con valores espaciados uniformemente

np_arange = np.arange(0, 10, 2)
np_arange

array([0, 2, 4, 6, 8])

In [12]:
# np.add() suma 2 array

arr1 = np.array([1,5,7])
arr2 = np.array([2,4,6])

# sumar array
suma_array = np.add(arr1, arr2)
suma_array

resta_array = np.subtract(arr1, arr2)
resta_array

#dividir Array
division_array = np.divide(arr1, arr2)
division_array

# Multiplicar
multi_arr = np.multiply(arr1, arr2)
multi_arr

# Producto entre 2 array
prod_arr = np.dot(arr1,arr2)
prod_arr

64